name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew@sha256:106ad024016ef0776cbfd99b27fb30c849de62fe374653680fd7a0f19245e078
    steps:
    - name: Install cmake
      run: |
        apk add cmake

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Fetch full clone
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow

    - name: Compile non-VFS version
      id: make
      run: |
        cmake -B build
        cmake --build build

    - name: Compile VFS version
      id: make-vfs
      run: |
        cmake -B build -DEMBED_VFS=ON -DOUTDIR=release_vfs
        cmake --build build
        rm -rf build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: steps.make.outcome == 'success'
      with:
        name: artifacts
        path: |
          release/**
          release_vfs/**
